### ISSUE TITLE
Monitor disk usage on separate volume

### ISSUE THREAD

**Issue by bkeroackdsc** [DataDog/docker-dd-agent#112]
On some of my systems ``/var/lib/docker`` is a tmpfs ramdisk. I want to monitor free space on it. Is this possible?

I've mounted it into the dd-agent container: ``-v /var/lib/docker:/ramdisk:ro``

However I'm not seeing any metric other than ``system.disk.free``.  Any tips?

**Comment by hkaj** [comment]
Hi @bkeroackdsc 
Thanks for reaching out, I think what you're looking for is the `use_mount` option. The metric is probably collected already, it just shows up under the `tmpfs` device tag because if `use_mount` is false (it is by default) the device tag is the filesystem, not the mount point.

You can find this option here: https://github.com/DataDog/dd-agent/blob/5.8.5/conf.d/disk.yaml.default and the behavior I described here: https://github.com/DataDog/dd-agent/blob/5.8.5/checks.d/disk.py#L106

To modify the option you can build your own image based on ours and modify the config file there, or use this feature: https://github.com/DataDog/docker-dd-agent#enabling-integrations to add your own `disk.yaml` with `use_mount: yes`.

Let me know how that goes.

**Comment by hkaj** [comment]
Closing as it should be solved. If not feel free to reopen.
