### ISSUE TITLE
Couldn't launch JMXTerm. Is Java in your PATH ?

### ISSUE THREAD

**Issue by xufeibuaa** [DataDog/docker-dd-agent#148]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
(paste your output here)
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1. configure tomcat.yaml
2. restart docker-dd-agent container
3.

**Describe the results you received:**
service datadog-agent info:
![image](https://cloud.githubusercontent.com/assets/17919255/21344510/0f7be3f6-c6d7-11e6-952b-92c3e2101523.png)

**Describe the results you expected:**
![image](https://cloud.githubusercontent.com/assets/17919255/21344529/2a3a89a4-c6d7-11e6-91a1-ce0be1d3b4ce.png)

**Additional information you deem important (e.g. issue happens only occasionally):**
The result I expected can be got if I run datadog agent in process not container. 
I install oracle-java8 in my machine.
I would like to know whether it is because java not installed in the Dockerfile ?

**Comment by hkaj** [comment]
Hi @xufeibuaa 
thanks for the detailed report.
Indeed this is due to Java not being installed in the container. Shipping it by default would make the image bigger and a lot of users don't need it so we prefer not doing it.
You can make JMX monitoring work by creating a new image based on ours and installing `openjdk-7-jre-headless` in it.
Let us know if you have any other question.

**Comment by hkaj** [comment]
Closing as it should be fixed.
