### ISSUE TITLE
pycurl missing from Alpine image

### ISSUE THREAD

**Issue by micahlmartin** [DataDog/docker-dd-agent#166]
Running this version:

datadog/docker-dd-agent:11.1.5101-alpine

Seeing this error:

```
dd-agent is configured to use the Curl HTTP Client, but pycurl is not available on this system.
/opt/datadog-agent # python
```

Confirmed that the package is indeed missing:

```
/opt/datadog-agent # python
Python 2.7.12 (default, Jun 29 2016, 08:57:23)
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pycurl
>>>
```

**Comment by hkaj** [comment]
Hi @micahlmartin, thanks for the report.

The agent uses a virtualenv\[0\], so you're probably not using the right python here. Can you try with `/opt/datadog-agent/venv/bin/python`? Importing pycurl here should raise `ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)`, which is fixed by #168.

Thanks again for raising this issue.

\[0\]: yeah that doesn't make much sense in a container, but the alpine image is just running our default source install script right now.
