### ISSUE TITLE
Unable to mount /proc in Docker Cloud

### ISSUE THREAD

**Issue by duizendnegen** [DataDog/docker-dd-agent#202]
Mounting `/proc` to `/host/proc` gives:

`ERROR: dev-datadog-agent-1: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: \"/var/lib/docker/aufs/mnt/f5a45d57ed73f4b31522102772b415061d2427870b310675b0509e9c43893c18/proc\" cannot be mounted because it is located inside \"/proc\""`

I'm using `datadog/docker-dd-agent:latest` in Docker Cloud, switched on privileged mode (just in case that was needed). Dropping that volume mount things work, but I'm pretty sure the Docker integration doesn't work as intended then.

**Comment by lgelfan** [comment]
Having the same issue, host target node is Debian 3.16

**Comment by duizendnegen** [comment]
Our host target was Ubuntu 14.04

**Comment by xigang** [comment]
same problem.

**Comment by irabinovitch** [comment]
We definitely want to mount /proc as that is where we pull in the data needed for the [live container view](https://www.datadoghq.com/blog/introducing-live-container-monitoring/) among other features.  

@hkaj did we have a chance to look into this?

**Comment by hkaj** [comment]
@irabinovitch, all,

We queued some work to check what needs to be done in order to make the agent work on Docker Cloud (be it documentation, or code changes). Stay tuned.

**Comment by kimroen** [comment]
I just wanted to provide some extra insight into this! In our case, we were seeing this error and it turned out that we had put the arguments for where to mount the volumes the wrong way around. It's kind of confusing, because the container and host arguments for mounting volumes are reversed in the UI compared to what they are when using the CLI, so that could be something to make sure you got right.

It should look like this:

![Docker Cloud interface for adding volumes](https://user-images.githubusercontent.com/520420/36908629-0aaef03a-1e3c-11e8-88ae-4d0ada71f863.png)

**Comment by kimroen** [comment]
This can probably be closed, considering [this aspect of Docker Cloud is shutting down on May 21st](https://docs.docker.com/docker-cloud/migration/).

**Comment by hkaj** [comment]
indeed, closing.
