### ISSUE TITLE
[dev] Request for major version changelog

### ISSUE THREAD

**Issue by willmore** [DataDog/docker-dd-agent#240]
The [Versioning](https://github.com/DataDog/docker-dd-agent#versioning-pattern) section of the README outlines the X.Y.Z versioning format, but does not describe what might constitutive a major version change.

Currently we are updating from 11.x.z to 12.x.z - what do we know about the major version change?

**Comment by xvello** [comment]
Hi @willmore ,

Indeed, we should have a readme, I'm make sure that happens shortly.

As far as 12.x.x is concerned, we bumped the major version after [our complete dockerfile/entrypoint refactoring](https://github.com/DataDog/docker-dd-agent/pull/222). It was more of a precaution as it should not break any compatibility.

Please note that 12.3.5172 disables the supervisorctl port, so you need to use `/probe.sh` instead of the http healthcheck if you use it.


Regards

**Comment by hkaj** [comment]
for future releases: #247
