### ISSUE TITLE
There is apparently no way to disable collection of kube-state-metrics

### ISSUE THREAD

**Issue by erkolson** [DataDog/docker-dd-agent#246]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
====================
Collector (v 5.17.2)
====================

  Status date: 2017-09-29 21:48:15 (10s ago)
  Pid: 27
  Platform: Linux-4.4.65-k8s-x86_64-with-debian-8.9
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: 0.0019 s
    System UTC time: 2017-09-29 21:48:25.820824

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    ec2-hostname: ip-172-17-164-8.ec2.internal
    local-ipv4: 172.17.164.8
    socket-hostname: datadog-dd-agent-f0m5s
    hostname: i-008f1a1211c2b3e08
    local-hostname: ip-172-17-164-8.ec2.internal
    instance-id: i-008f1a1211c2b3e08
    socket-fqdn: datadog-dd-agent-f0m5s

  Checks
  ======

    ntp (5.17.2)
    ------------
      - Collected 0 metrics, 0 events & 0 service checks

    disk (5.17.2)
    -------------
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 0 service checks

    kubernetes (5.17.2)
    -------------------
      - instance #0 [OK]
      - Collected 258 metrics, 0 events & 3 service checks

    docker_daemon (5.17.2)
    ----------------------
      - instance #0 [OK]
      - Collected 189 metrics, 1 event & 1 service check


  Emitters
  ========

    - http_emitter [OK]

2017-09-29 21:48:27,464 | WARNING | dd.dogstatsd | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
====================
Dogstatsd (v 5.17.2)
====================

  Status date: 2017-09-29 21:48:17 (9s ago)
  Pid: 17
  Platform: Linux-4.4.65-k8s-x86_64-with-debian-8.9
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 326
  Packet Count: 4273
  Packets per second: 1.2
  Metric count: 12
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.17.2)
====================

  Status date: 2017-09-29 21:48:27 (1s ago)
  Pid: 16
  Platform: Linux-4.4.65-k8s-x86_64-with-debian-8.9
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 395 bytes
  Queue Length: 1
  Flush Count: 1131
  Transactions received: 822
  Transactions flushed: 821
  Transactions rejected: 0
  API Key Status: API Key is valid


======================
Trace Agent (v 5.17.2)
======================

  Pid: 15
  Uptime: 3328 seconds
  Mem alloc: 774296 bytes

  Hostname: datadog-dd-agent-f0m5s
  Receiver: 0.0.0.0:8126
  API Endpoint: https://trace.agent.datadoghq.com

  Bytes sent (1 min): 0
  Traces sent (1 min): 0
  Stats sent (1 min): 0
```

Kubernetes 1.7.4

**Steps to reproduce the issue:**
1.  Run the dd-agent in a daemonset with the default kubernetes integration enabled but default value for kube_metrics (disabled)

ALSO

1. Run the dd-agent with the default kubernetes integration with the ENV variable `KUBERNETES_COLLECT_EVENTS` set to `0` or `false`.  The configuration file `/etc/dd-agent/conf.d/kubernetes.yaml` ends up with `collect_events: true` 

**Describe the results you received:**
The description indicates that collecting kube state metrics from multiple agents is bad, could overwhelm the API servers.  It is clear that no matter what I do, a daemonset running dd-agents is collecting kube-state data.  The kube-state-metrics service enpoint is auto-discovered and being ingested.

**Describe the results you expected:**
I expected a `dd-agent` daemonset to not collect the kube-state-metrics with a default configuration, and definitely to not collect that data when explicitly disabled.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by hkaj** [comment]
Hi @erkolson, thanks for the feedback.

I think you're confusing two things here: kube-state-metrics is not being collected in the dd-agent info you pasted. Otherwise we would see a `kubernetes_state (5.17.2)` line in the output.

`kube-state-metrics` is also (normally) running only once per cluster. So you are right, it is auto-discovered by the agent, but since it should run on a single node, and there should be only one agent per node, its metrics should be collected only once  - by the agent running on the same node.

If you run `kube-state-metrics` from all your nodes that would query the apiserver more that's correct, but collecting the resulting metrics in the agent wouldn't change anything since we get them by querying the kube-state-metrics pod, not the apiserver.

Finally if you deploy the agent as a single daemon set, you are completely right: Kubernetes event collection (which is part of the kubernetes check, and does query the apiserver unlike kube-state-metrics) should be enabled on a single agent, not all of them. To make it easier we recommend using leader election as explained [here](https://github.com/DataDog/docker-dd-agent#environment-variables-1). You shouldn't set the KUBERNETES_COLLECT_EVENTS env variable at all, but rather use `KUBERNETES_LEADER_CANDIDATE` instead.

Hope that helps, let me know if you have any other question.

**Comment by erkolson** [comment]
Thank you!  Indeed, I was confusing `kube-state` and `kube events`.  I've updated the daemonset with `KUBERNETES_LEADER_CANDIDATE`... Curious, is there a way to determine which agent is the current leader?  I thought I read something about a configmap in use for elections but I don't see one.

**Comment by erkolson** [comment]
I couldn't find the configmap because the serviceaccount was not authorized to create them :-).

This is what I ended up binding to the serviceaccount used by the daemonset pods: 
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: dd-agent-configmaps
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - watch
- apiGroups:
  - ""
  resourceNames:
  - datadog-leader-elector
  resources:
  - configmaps
  verbs:
  - get
  - update
  - delete
```

**Comment by hkaj** [comment]
Glad you got it to work!
We just merged RBAC documentation, so for more info about that and other settings for the Kubernetes integration, see https://github.com/DataDog/integrations-core/blob/6db3fdfd0778e45202b2e82d297e26bd31d04a10/kubernetes/README.md
