### ISSUE TITLE
Alpine image is not sending "container metrics" in kubernetes cluster

### ISSUE THREAD

**Issue by felipejfc** [DataDog/docker-dd-agent#260]
The alpine image is not sending container specific metrics to follow in the new "Live Container Monitoring".

I've tested both alpine and normal images and only the normal one was sending container metrics do datadog on a AWS kubernetes cluster (dd-agent is deployed as a daemonset with no custom configs between the two tests).

**Comment by lachlancooper** [comment]
I'm seeing the same behaviour difference between alpine and normal images in a Docker Swarm cluster, image version 12.4.5202. The alpine container becomes healthy and according to the logs successfully collects metrics and flushes transactions, but the Containers page shows "No Agents reporting!".

I'm happy to investigate further, but I don't know what component is responsible for the live container monitoring.

**Comment by ocraviotto** [comment]
This limitation is documented for both [Live Containers](https://docs.datadoghq.com/graphing/infrastructure/livecontainers/#notes-known-issues) 
> Live Containers is available for the default Debian docker-dd-agent image only. It is not included in the Alpine image.

and [Live Process](https://docs.datadoghq.com/graphing/infrastructure/process/#notes-and-frequently-asked-questions)
> The Process Agent is available for the default Debian docker-dd-agent image only. It is not included in the Alpine image.

As you can see this is due to the [process agent](https://github.com/DataDog/datadog-process-agent) missing in the alpine based docker dd-agent. 

I've successfully got the process-agent installed in our alpine based dd-agent (a modified DataDog docker-dd-agent using our base docker image and running on DCOS clusters) and sending data to the process endpoint, so live containers and live processes are both working. So far I've had it running on our test env for a few hours and it's been OK.

Once I have the changes pushed into our public github dd-agent repo I'll post a link here for anyone who might be interested to have a look.

**Comment by xvello** [comment]
Hi @felipejfc,

As the `process-agent` is a go binary, it is only supported in the debian-based images, same as the `trace-agent` / APM agent. As alpine uses `musl` instead of the `glibc`, go binaries built on debian cannot run on alpine.

We are currently investigating the creation of an alpine build pipeline, but for now our focus is to bring our debian and centos runnners to full speed before adding a third pipeline. This is why I cannot communicate on an ETA yet.

Could you please tell me if running the debian image has any drawbacks for your workflow?

**Comment by ocraviotto** [comment]
An example of a *running process agent* Dockerfile/configuration in alpine can be found here: https://github.com/comptelfwd/dd-agent/tree/5.20.2-2
And yes, the binary does run in alpine (we simply symlink musl and glibc so in our [base image](https://github.com/comptelfwd/docker-alpine-base/blob/2c9efca30ae2dc7a9b373695baeba58960984b20/Dockerfile#L17) )
