### ISSUE TITLE
Can I run docker-dd-agent without supervisor?

### ISSUE THREAD

**Issue by gtaylor** [DataDog/docker-dd-agent#46]
I'd rather let Kubernetes handle this and not deal with supervisor.

**Comment by remh** [comment]
@gtaylor sorry for the delay.

You would rather have multiple containers for the agent instead ? one for each process ?
That's doable but a bit tricky to get the network configuration right. We will investigate.

**Comment by gtaylor** [comment]
I'd just like to run the process directly, rather than have supervisord run the process within the container. I already get process supervision with Kubernetes, so supervisord is doing nothing but making the container act different than my other systems.

**Comment by remh** [comment]
The thing though is that the agent is running multiple processes, see the agent architecture:
https://github.com/DataDog/dd-agent/wiki/Agent%20Architecture

That's why the supervisor is required. We could change that and have one process per container but it would be more work to deploy (2-3 or containers instead of one)

**Comment by gtaylor** [comment]
Ah, I see. 

Is this the supervisor config I'd need to pick apart to run all of these directly? https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/supervisord.conf

**Comment by remh** [comment]
This is the one used in the container
https://github.com/DataDog/dd-agent/blob/master/packaging/supervisor.conf

**Comment by gtaylor** [comment]
Cool, thanks!
