### ISSUE TITLE
Consider reducing image size

### ISSUE THREAD

**Issue by therc** [DataDog/docker-dd-agent#75]
Right now the container uses Debian Jessie. This means there's stuff like Perl, locales and a lot more (systemd, etc.). Then, because of `/opt/datadog-agent/embedded`, there are lots of duplicate binaries: which, top, touch (probably not needed by the agent), but also update-alternatives, dpkg-divert, ncurses5-config, captoinfo and many more (very likely to be unnecessary) :-)

Possible solutions:
 - start from a smaller base image, such as Busybox or Alpine
 - use a two-step approach, where the first sets up the build and just outputs what's needed at runtime, to be packaged in the second step as the final image.

**Comment by hkaj** [comment]
Hi @therc 
We're actually working on an alpine-based image right now, both for its light weight and the hardened security. It doesn't reduce the size of the image much for now because of the way we ship dependencies, but that's the first step. We're looking at other actions we could take to improve this, so stay tuned ;)

**Comment by hkaj** [comment]
@therc sorry for the long wait, I hope the new `alpine` tag solves this issue :) https://hub.docker.com/r/datadog/docker-dd-agent/tags/

I'm going to close this issue now, feel free to re-open or create a new one if you have any other question.
